import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";

// 1. Import your new ThemeProvider client component
import { ThemeProvider } from "./theme-provider"; 

const inter = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Doweit",
  description: "Generated by Doweit",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          {/* 2. Use your new ThemeProvider component here */}
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange // Optional but recommended for smoother transitions
          >
            <Toaster position="top-right" />
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}