import { Outfit } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

// 1. Import your new ThemeProvider client component
import { ThemeProvider } from "./theme-provider";
// Global "site assistant" — the floating chat widget that lets users navigate
// the app by voice. No-op when NEXT_PUBLIC_DOWEIT_SITE_PUBLIC_KEY is not set,
// so the rest of the app keeps working without the one-time setup.
import SiteAssistant from "./_components/SiteAssistant";

const inter = Outfit({ subsets: ["latin"] });

export const metadata = {
	title: "Doweit",
	description: "Generated by Doweit",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={inter.className}>
				{/* 2. Use your new ThemeProvider component here */}
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange // Optional but recommended for smoother transitions
				>
					<Toaster position="top-right" />
					{children}
					<SiteAssistant />
				</ThemeProvider>
			</body>
		</html>
	);
}

