// ─── Trainee Demo Data ──────────────────────────────────────────
export const demoStats = {
  totalSessions: 42,
  avgScore: 78,
  xpPoints: 3840,
  level: 7,
  streak: 5,
  rank: 'Gold',
  sessionsThisMonth: 12,
  improvementRate: 14,
};

export const weeklyProgress = [
  { day: 'Mon', score: 62, sessions: 1 },
  { day: 'Tue', score: 75, sessions: 2 },
  { day: 'Wed', score: 70, sessions: 1 },
  { day: 'Thu', score: 83, sessions: 3 },
  { day: 'Fri', score: 78, sessions: 2 },
  { day: 'Sat', score: 88, sessions: 2 },
  { day: 'Sun', score: 85, sessions: 1 },
];

export const monthlyScores = [
  { month: 'Jan', avg: 62 },
  { month: 'Feb', avg: 67 },
  { month: 'Mar', avg: 71 },
  { month: 'Apr', avg: 75 },
  { month: 'May', avg: 78 },
];

export const skillData = [
  { skill: 'Technical', score: 82 },
  { skill: 'Behavioral', score: 74 },
  { skill: 'Communication', score: 88 },
  { skill: 'Problem Solving', score: 71 },
  { skill: 'Leadership', score: 65 },
  { skill: 'System Design', score: 60 },
];

export const categoryBreakdown = [
  { name: 'Mock Interview', value: 18, color: '#7c3aed' },
  { name: 'Quiz', value: 14, color: '#2563eb' },
  { name: 'System Design', value: 6, color: '#4f46e5' },
  { name: 'Behavioral', value: 4, color: '#0ea5e9' },
];

export const recentSessions = [
  { id: 1, agent: 'Alex — Senior Eng', type: 'Mock Interview', score: 84, duration: '28 min', date: '2026-05-07', status: 'completed', topic: 'React & Frontend' },
  { id: 2, agent: 'Sarah — HR Specialist', type: 'Behavioral', score: 91, duration: '22 min', date: '2026-05-06', status: 'completed', topic: 'Leadership Stories' },
  { id: 3, agent: 'Viktor — SWE', type: 'Quiz', score: 73, duration: '15 min', date: '2026-05-05', status: 'completed', topic: 'Data Structures' },
  { id: 4, agent: 'Alex — Senior Eng', type: 'Mock Interview', score: 68, duration: '31 min', date: '2026-05-04', status: 'completed', topic: 'System Design' },
  { id: 5, agent: 'Sarah — HR Specialist', type: 'Mock Interview', score: 79, duration: '25 min', date: '2026-05-03', status: 'completed', topic: 'Culture Fit' },
];

// ─── Sessions (MySessions) ───────────────────────────────────────
export const demoSessions = [
  { id: 1,  title: 'React Frontend Interview',  agent: 'Alex',  type: 'Mock Interview',  score: 84, duration: 28,  date: '2026-05-07', status: 'completed', topic: 'Frontend', difficulty: 'Medium', questions: 8  },
  { id: 2,  title: 'Leadership & Culture Fit',   agent: 'Sarah', type: 'Behavioral',       score: 91, duration: 22,  date: '2026-05-06', status: 'completed', topic: 'Behavioral', difficulty: 'Easy',   questions: 6  },
  { id: 3,  title: 'Data Structures Quiz',        agent: 'Viktor',type: 'Quiz',             score: 73, duration: 15,  date: '2026-05-05', status: 'completed', topic: 'CS Fundamentals', difficulty: 'Hard', questions: 10 },
  { id: 4,  title: 'System Design Deep Dive',     agent: 'Alex',  type: 'Mock Interview',   score: 68, duration: 31,  date: '2026-05-04', status: 'completed', topic: 'System Design', difficulty: 'Hard', questions: 5  },
  { id: 5,  title: 'Product Management Basics',   agent: 'Maya',  type: 'Mock Interview',   score: 80, duration: 26,  date: '2026-05-02', status: 'completed', topic: 'Product', difficulty: 'Medium', questions: 8  },
  { id: 6,  title: 'Python Fundamentals Quiz',    agent: 'Viktor',type: 'Quiz',             score: 95, duration: 12,  date: '2026-04-30', status: 'completed', topic: 'Python', difficulty: 'Easy',   questions: 15 },
  { id: 7,  title: 'Conflict Resolution Practice',agent: 'Sarah', type: 'Behavioral',       score: 77, duration: 20,  date: '2026-04-28', status: 'completed', topic: 'Behavioral', difficulty: 'Medium', questions: 6 },
  { id: 8,  title: 'Full-Stack Interview Prep',   agent: 'Alex',  type: 'Mock Interview',   score: 71, duration: 35,  date: '2026-04-25', status: 'completed', topic: 'Full-Stack', difficulty: 'Hard', questions: 10 },
  { id: 9,  title: 'SQL & Database Quiz',         agent: 'Viktor',type: 'Quiz',             score: 88, duration: 18,  date: '2026-04-22', status: 'completed', topic: 'Databases', difficulty: 'Medium', questions: 12 },
  { id: 10, title: 'Startup Culture Interview',   agent: 'Maya',  type: 'Mock Interview',   score: 82, duration: 24,  date: '2026-04-20', status: 'completed', topic: 'Culture', difficulty: 'Easy', questions: 7  },
];

// ─── Marketplace Agents ─────────────────────────────────────────
export const demoAgents = [
  {
    id: 'alex-01',
    name: 'Alex',
    title: 'Senior Software Engineer',
    category: 'Technical',
    specialties: ['React', 'Node.js', 'System Design'],
    difficulty: 'Hard',
    rating: 4.9,
    sessions: 1248,
    tokenCost: 50,
    duration: '25–35 min',
    description: 'Alex specializes in deep technical interviews covering frontend, backend, and system design. Known for challenging but fair questioning.',
    featured: true,
    avatar: 'A',
    color: 'from-purple-500 to-blue-500',
  },
  {
    id: 'sarah-02',
    name: 'Sarah',
    title: 'HR & Culture Specialist',
    category: 'Behavioral',
    specialties: ['Leadership', 'Culture Fit', 'Communication'],
    difficulty: 'Easy',
    rating: 4.8,
    sessions: 987,
    tokenCost: 40,
    duration: '20–25 min',
    description: 'Sarah guides you through behavioral and culture-fit interviews. Great for STAR-method practice and soft-skill development.',
    featured: true,
    avatar: 'S',
    color: 'from-blue-500 to-indigo-500',
  },
  {
    id: 'viktor-03',
    name: 'Viktor',
    title: 'CS Fundamentals Coach',
    category: 'Quiz',
    specialties: ['Algorithms', 'Data Structures', 'Python'],
    difficulty: 'Medium',
    rating: 4.7,
    sessions: 2341,
    tokenCost: 30,
    duration: '10–20 min',
    description: 'Viktor runs rapid-fire quizzes on CS fundamentals, algorithms, and data structures. Perfect for quick knowledge checks.',
    featured: false,
    avatar: 'V',
    color: 'from-indigo-500 to-purple-500',
  },
  {
    id: 'maya-04',
    name: 'Maya',
    title: 'Product Management Expert',
    category: 'Product',
    specialties: ['Product Strategy', 'Metrics', 'User Research'],
    difficulty: 'Medium',
    rating: 4.6,
    sessions: 543,
    tokenCost: 45,
    duration: '20–30 min',
    description: 'Maya covers product thinking, metrics, roadmapping, and stakeholder management. Ideal for PM interview preparation.',
    featured: false,
    avatar: 'M',
    color: 'from-violet-500 to-purple-600',
  },
  {
    id: 'kai-05',
    name: 'Kai',
    title: 'System Design Architect',
    category: 'Technical',
    specialties: ['Distributed Systems', 'Databases', 'Scalability'],
    difficulty: 'Hard',
    rating: 4.8,
    sessions: 712,
    tokenCost: 60,
    duration: '30–45 min',
    description: 'Kai specializes in large-scale system design questions. Tests your ability to architect scalable, reliable distributed systems.',
    featured: false,
    avatar: 'K',
    color: 'from-blue-600 to-cyan-500',
  },
  {
    id: 'nina-06',
    name: 'Nina',
    title: 'DevOps & Cloud Specialist',
    category: 'Technical',
    specialties: ['AWS', 'Docker', 'CI/CD'],
    difficulty: 'Hard',
    rating: 4.5,
    sessions: 389,
    tokenCost: 50,
    duration: '25–35 min',
    description: 'Nina covers cloud infrastructure, DevOps practices, and CI/CD pipelines. Perfect for SRE and DevOps interview prep.',
    featured: false,
    avatar: 'N',
    color: 'from-sky-500 to-blue-600',
  },
];

// ─── Library Templates ──────────────────────────────────────────
export const demoTemplates = [
  {
    id: 'tpl-01',
    title: 'FAANG Technical Round',
    topic: 'Algorithms & Problem Solving',
    category: 'Technical',
    questionCount: 8,
    duration: 45,
    difficulty: 'Hard',
    sessions: 234,
    description: 'Simulates a typical FAANG technical phone screen with LeetCode-style questions and system design.',
    agent: 'Alex',
    createdAt: '2026-04-10',
    tags: ['Algorithms', 'LeetCode', 'FAANG'],
  },
  {
    id: 'tpl-02',
    title: 'Behavioral Star Method',
    topic: 'Leadership & Teamwork',
    category: 'Behavioral',
    questionCount: 6,
    duration: 25,
    difficulty: 'Easy',
    sessions: 512,
    description: 'Practice the STAR method with common behavioral questions around leadership, conflict, and teamwork.',
    agent: 'Sarah',
    createdAt: '2026-04-05',
    tags: ['STAR', 'Leadership', 'Culture Fit'],
  },
  {
    id: 'tpl-03',
    title: 'System Design Basics',
    topic: 'Distributed Systems',
    category: 'Technical',
    questionCount: 5,
    duration: 40,
    difficulty: 'Medium',
    sessions: 187,
    description: 'Design systems like a URL shortener, chat app, or news feed. Build your architecture thinking.',
    agent: 'Kai',
    createdAt: '2026-03-28',
    tags: ['Scalability', 'Architecture', 'Databases'],
  },
  {
    id: 'tpl-04',
    title: 'Python Quick Fire',
    topic: 'Python & Data Structures',
    category: 'Quiz',
    questionCount: 15,
    duration: 15,
    difficulty: 'Easy',
    sessions: 741,
    description: 'Rapid-fire Python knowledge quiz covering syntax, libraries, OOP, and common coding patterns.',
    agent: 'Viktor',
    createdAt: '2026-03-15',
    tags: ['Python', 'OOP', 'Libraries'],
  },
  {
    id: 'tpl-05',
    title: 'PM Product Sense',
    topic: 'Product Strategy & Metrics',
    category: 'Product',
    questionCount: 7,
    duration: 30,
    difficulty: 'Medium',
    sessions: 156,
    description: 'Test your product sense with questions about feature prioritization, metrics, and user empathy.',
    agent: 'Maya',
    createdAt: '2026-03-01',
    tags: ['Product', 'Metrics', 'Strategy'],
  },
  {
    id: 'tpl-06',
    title: 'AWS Cloud Practitioner',
    topic: 'Cloud & Infrastructure',
    category: 'Technical',
    questionCount: 10,
    duration: 30,
    difficulty: 'Medium',
    sessions: 98,
    description: 'Practice AWS, Docker, and cloud concepts. Prepare for DevOps and cloud engineer interviews.',
    agent: 'Nina',
    createdAt: '2026-02-20',
    tags: ['AWS', 'Cloud', 'DevOps'],
  },
];

// ─── Quiz Questions ─────────────────────────────────────────────
export const demoQuizQuestions = {
  'Mock Interview': [
    { id: 1, question: 'What is the difference between REST and GraphQL?', options: ['REST uses fixed endpoints; GraphQL uses a single flexible endpoint', 'GraphQL is faster than REST in all cases', 'REST supports real-time subscriptions natively', 'GraphQL requires a specific database type'], answer: 0, explanation: 'REST uses multiple fixed endpoints per resource, while GraphQL exposes one endpoint and lets clients specify exactly what data they need.' },
    { id: 2, question: 'Which HTTP method is idempotent but NOT safe?', options: ['GET', 'PUT', 'POST', 'PATCH'], answer: 1, explanation: 'PUT is idempotent (calling it multiple times produces the same result) but not safe because it modifies server state.' },
    { id: 3, question: 'What does SOLID stand for in software design?', options: ['Single, Open, Liskov, Interface, Dependency', 'Scalable, Open, Linear, Integration, Data', 'Single, Object, Liskov, Interface, Dependency', 'Scalable, Optimized, Linked, Integrated, Distributed'], answer: 0, explanation: 'SOLID: Single Responsibility, Open/Closed, Liskov Substitution, Interface Segregation, Dependency Inversion.' },
    { id: 4, question: 'Which data structure offers O(1) average-case lookup?', options: ['Linked List', 'Binary Tree', 'Hash Map', 'Stack'], answer: 2, explanation: 'Hash maps use hash functions to index keys, achieving O(1) average-case lookup (O(n) worst case due to collisions).' },
    { id: 5, question: 'What is the primary purpose of an index in a database?', options: ['To compress data', 'To speed up read queries', 'To enforce uniqueness', 'To create foreign key relations'], answer: 1, explanation: 'Indexes create a separate data structure (B-tree or hash) allowing the DB engine to locate rows without a full table scan.' },
    { id: 6, question: 'In React, what triggers a component re-render?', options: ['Only state changes', 'State or prop changes', 'Any function call inside the component', 'Every 16ms via the event loop'], answer: 1, explanation: 'React re-renders when state or props change. Context changes also trigger re-renders for subscribed components.' },
    { id: 7, question: 'What is the time complexity of quicksort in the average case?', options: ['O(n)', 'O(n log n)', 'O(n²)', 'O(log n)'], answer: 1, explanation: 'Quicksort has O(n log n) average case complexity. The worst case is O(n²) when the pivot is always the smallest or largest element.' },
    { id: 8, question: 'Which design pattern creates objects without specifying exact class?', options: ['Singleton', 'Observer', 'Factory', 'Decorator'], answer: 2, explanation: 'The Factory pattern defines an interface for creating objects, letting subclasses decide which class to instantiate.' },
  ],
  'Behavioral': [
    { id: 1, question: 'The STAR method stands for:', options: ['Situation, Task, Action, Result', 'Strategy, Target, Approach, Review', 'Skill, Team, Ability, Response', 'Story, Timeline, Achievement, Reflection'], answer: 0, explanation: 'STAR is an interview technique: Situation (context), Task (your role), Action (what you did), Result (outcome).' },
    { id: 2, question: 'When asked "Tell me about a time you failed", interviewers want to know:', options: ['That you never make mistakes', 'How you learn and recover from setbacks', 'That failures are always someone else\'s fault', 'That you avoid risky situations'], answer: 1, explanation: 'This question assesses self-awareness, accountability, and growth mindset — not that you\'re perfect.' },
    { id: 3, question: 'Which is the best way to answer "What is your greatest weakness?"', options: ['Say you have no weaknesses', 'Name a real weakness you\'re actively improving', 'Turn a strength into a fake weakness', 'Refuse to answer personal questions'], answer: 1, explanation: 'Honest self-awareness + evidence of improvement shows maturity and genuine self-reflection.' },
    { id: 4, question: 'What does "culture fit" typically measure in interviews?', options: ['Your technical skill level', 'Whether your values and work style align with the company', 'Your salary expectations', 'How many years of experience you have'], answer: 1, explanation: 'Culture fit assesses whether your values, communication style, and working preferences align with the team environment.' },
    { id: 5, question: 'When describing conflict resolution, you should emphasize:', options: ['How you were right and the other person was wrong', 'Avoiding conflict entirely', 'Listening, empathizing, and finding collaborative solutions', 'Escalating to management immediately'], answer: 2, explanation: 'Effective conflict resolution demonstrates emotional intelligence, active listening, and collaborative problem-solving.' },
    { id: 6, question: 'A growth mindset means believing:', options: ['Intelligence is fixed at birth', 'Abilities can be developed through dedication', 'Hard work doesn\'t matter, only talent does', 'You should avoid challenges to protect your ego'], answer: 1, explanation: 'Coined by Carol Dweck, growth mindset is the belief that skills and intelligence can grow through effort and learning.' },
  ],
  'Quiz': [
    { id: 1, question: 'What is Big O notation used for?', options: ['Measuring memory usage only', 'Describing algorithm time/space complexity', 'Counting lines of code', 'Measuring CPU clock speed'], answer: 1, explanation: 'Big O notation describes the upper bound of an algorithm\'s time or space complexity as input size grows.' },
    { id: 2, question: 'A stack follows which principle?', options: ['FIFO (First In First Out)', 'LIFO (Last In First Out)', 'Random access', 'Priority-based access'], answer: 1, explanation: 'Stacks use LIFO — the last element pushed is the first one popped, like a stack of plates.' },
    { id: 3, question: 'What does DRY stand for in programming?', options: ['Dynamic Runtime Yielding', "Don't Repeat Yourself", 'Data Redundancy Yield', 'Dynamic Resource Yarding'], answer: 1, explanation: "DRY principle: Don't Repeat Yourself — every piece of knowledge should have a single, authoritative representation." },
    { id: 4, question: 'In binary search, the prerequisite is:', options: ['The array must be sorted', 'The array must have even length', 'All elements must be unique', 'The array must be in memory'], answer: 0, explanation: 'Binary search only works on sorted arrays — it relies on comparing the middle element to narrow the search range.' },
    { id: 5, question: 'What is a closure in programming?', options: ['A way to close file handles', 'A function that retains access to its outer scope variables', 'A sealed class in OOP', 'A method to terminate loops'], answer: 1, explanation: 'A closure is a function bundled with references to its surrounding lexical scope — it "closes over" variables from the outer function.' },
    { id: 6, question: 'Which sorting algorithm is stable and has O(n log n) worst-case?', options: ['Quick Sort', 'Heap Sort', 'Merge Sort', 'Bubble Sort'], answer: 2, explanation: 'Merge Sort is stable (preserves equal element order) and always runs in O(n log n), unlike quicksort which can degrade to O(n²).' },
    { id: 7, question: 'What is the purpose of a mutex?', options: ['To speed up rendering', 'To prevent race conditions via mutual exclusion', 'To compress network packets', 'To handle memory leaks'], answer: 1, explanation: 'A mutex (mutual exclusion lock) ensures only one thread can access a shared resource at a time, preventing race conditions.' },
    { id: 8, question: 'TCP vs UDP — which guarantees delivery?', options: ['UDP', 'Both', 'TCP', 'Neither'], answer: 2, explanation: 'TCP provides guaranteed, ordered delivery via acknowledgments and retransmission. UDP is faster but connectionless with no delivery guarantee.' },
  ],
};

// ─── Token Transactions ─────────────────────────────────────────
export const demoTransactions = [
  { id: '1', type: 'purchase', amount: 2000, date: '2026-05-01', status: 'completed', description: 'Professional Pack Purchase' },
  { id: '2', type: 'usage',    amount: -50,  date: '2026-05-07', status: 'completed', description: 'Mock Interview — React Frontend' },
  { id: '3', type: 'usage',    amount: -40,  date: '2026-05-06', status: 'completed', description: 'Behavioral Session — Leadership' },
  { id: '4', type: 'bonus',    amount: 100,  date: '2026-05-05', status: 'completed', description: 'Weekly Streak Bonus (5 days)' },
  { id: '5', type: 'usage',    amount: -30,  date: '2026-05-05', status: 'completed', description: 'Quiz — Data Structures' },
  { id: '6', type: 'bonus',    amount: 50,   date: '2026-04-28', status: 'completed', description: 'Level Up Reward — Level 7' },
  { id: '7', type: 'usage',    amount: -50,  date: '2026-04-25', status: 'completed', description: 'Mock Interview — Full-Stack' },
];
